name: Bukkitmanager
main: me.efreak1996.BukkitManager.Bukkitmanager
version: 1.2
website: http://www.bukkit.org
author: efreak1996
description: >
             A plugin to update and manage bukkit and its plugins
commands:
  bm:
    description: Update and manage Bukkit
    usage: Use /bm help for more Help
permissions:
    bm.*:
        description: Gives access to all Bukkitmanager commands
        children:
            bm.plugin.*: true
            bm.bukkit.*: true
            bm.config: true
            bm.help: true
            bm.gui.admin: true
    bm.plugin.*:
        description: Gives access to all /bm plugin commands
        children:
            bm.plugin.enable: true
            bm.plugin.disable: true
            bm.plugin.restart: true
            bm.plugin.config: true
            bm.plugin.info: true
            bm.plugin.list: true
            bm.plugin.download: true
            bm.plugin.install: true
            bm.plugin.update: true
    bm.bukkit.*:
        description: Gives acces to all /bm bukkit commands
        children:
            bm.bukkit.info: true
            bm.bukkit.update: true
            bm.bukkit.config: true
    bm.config:
        description: Allows to use /bm config
        default: op
    bm.plugin.enable:
        description: Allows to enable Plugins
        default: op
    bm.plugin.disable:
        description: Allows to disable Plugins
        default: op
    bm.plugin.restart:
        description: Allows to restart Plugins
        default: op
    bm.plugin.info:
        description: Allows to view Infos about Plugins
        default: op
    bm.plugin.list:
        description: Allows to view a List of all Plugins
        default: true
    bm.plugin.download:
        description: Allows to download a Plugin
        default: true
    bm.plugin.install:
        description: Allows to install a Plugin
        default: true
    bm.plugin.update:
        description: Allows to update a Plugin
        default: true
    bm.plugin.config:
        description: Allows to change the Plugin config.yml
        default: true
    bm.bukkit.info:    
        description: Allows to view Server infos
        default: op
    bm.bukkit.update:    
        description: Allows to update the server
        default: op
    bm.bukkit.config:
        description: Allows to Edit the Serverconfigs
        default: op
    bm.help:
        description: Allows to view the Help
        default: op
    bm.gui.admin:
        descriprion: Allows to view the Admin Gui
        default: op
    bm.gui.supporter:
        description: Allows to view the Supporter Gui
        default: false
    bm.gui.vip:
        description: Allows to view the VIP Gui
        default: false
    bm.gui.member:
        description: Allows to view the Member Gui
        default: true
    bm.gui.guest:
        description: Allows to view the Guest Gui
        default: false